name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Android SDK + licenties + build-tools
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 31
          cmake: "3.22.1"
          ndk: 25.1.8937393
          cmdline-tools-version: latest

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install required SDK packages
        run: |
          sdkmanager "platform-tools" "platforms;android-31" "build-tools;35.0.0"

      - name: Install system deps
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk autoconf automake libtool pkg-config cmake

      - name: Install Buildozer (Python)
        run: |
          python -m pip install --upgrade pip
          pip install cython==0.29.36 buildozer

      - name: Generate assets (optional)
        run: |
          python make_assets.py || true
          ls -la assets || true
          ls -la sounds || true

      - name: Build debug APK
        env:
          USE_SDK_WRAPPER: "1"        # laat buildozer sdkmanager gebruiken
        run: |
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: DiverseyFlappy-APK
          path: bin/*.apk
